# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
android.useAndroidX=true
android.nonTransitiveRclass=true
android.nonTransitiveRClass=true
kotlin.incremental=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
