package com.healthtrack.app.data.fake

import com.healthtrack.app.data.model.DoseLog
import com.healthtrack.app.data.model.Medication
import com.healthtrack.app.data.repository.MedicationRepository
import com.healthtrack.app.util.Result
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map

class FakeMedicationRepository : MedicationRepository {
    private val medications = MutableStateFlow<List<Medication>>(emptyList())
    private val doseLogs = MutableStateFlow<List<DoseLog>>(emptyList())

    override fun getMedications(): Flow<List<Medication>> = medications

    override suspend fun addMedication(medication: Medication): Result<Unit> {
        medications.value = medications.value + medication
        return Result.Success(Unit)
    }

    override suspend fun updateMedication(medication: Medication): Result<Unit> {
        medications.value = medications.value.map { if (it.id == medication.id) medication else it }
        return Result.Success(Unit)
    }

    override suspend fun deleteMedication(medId: String): Result<Unit> {
        medications.value = medications.value.filter { it.id != medId }
        return Result.Success(Unit)
    }

    override fun getDoseLogsForDate(dateKey: String): Flow<List<DoseLog>> {
        // In reality, this should be generated by domain scheduler if not exists, 
        // but for fake repository, we just return what's saved.
        return doseLogs.map { list -> list.filter { it.id.contains(dateKey) } }
    }

    override suspend fun markDose(doseLog: DoseLog): Result<Unit> {
        val existing = doseLogs.value.find { it.id == doseLog.id }
        doseLogs.value = if (existing != null) {
            doseLogs.value.map { if (it.id == doseLog.id) doseLog else it }
        } else {
            doseLogs.value + doseLog
        }
        return Result.Success(Unit)
    }
}
